server/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from user_app import views as user_app_Views

router = routers.DefaultRouter()
router.register(r'users', user_app_Views.UserViewSet)
router.register(r'groups', user_app_Views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('api/user_app/', include('user_app.urls')),
    path('test/', include(router.urls)),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import html_views, api_views
app_name = 'shop_app'
router = routers.DefaultRouter()
router.register(r'products', api_views.ProductViewSet)
router.register(r'order_items', api_views.OrderItemViewSet)
router.register(r'orders', api_views.OrderViewSet)
urlpatterns = [
    url(r'^$', html_views.dashboard, name='dashboard'),
    url(r'^products/$', html_views.product_list, name='product_list'),
    url(r'^api/', include(router.urls)),
    url(r'^product/new$', html_views.new_product, name='new_product'),
    url(r'^product/delete/(?P<pk>\d+)/$', html_views.DeleteProduct.as_view(), name='delete_product'),
    url(r'^product/(?P<pk>\d+)/update/$', html_views.UpdateProduct.as_view(), name='update_product'),
    url(r'^orders/$', html_views.order_list, name='order_list'),
]

shop_app/models.py
from django.db import models
import os
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from enum import Enum
# Create your models here.


class Order(models.Model):
	ORDER_STATUS = (
		('New', 'New'),
		('Paid', 'Paid'),
		('Shipping', 'Shipping'),
		('Shipped', 'Shipped'),
		('Closed', 'Closed'),
	)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	status = models.CharField(max_length=10, choices=ORDER_STATUS, default='New',)

	@receiver(post_save, sender=User)
	def create_order(sender, instance, created, **kwargs):
		if created:
			Order.objects.create(user=instance, status='New')


class Product(models.Model):
	name = models.CharField(max_length=200, null=False)
	price = models.FloatField(null=False)
	available = models.BooleanField(default=False)
	img = models.CharField(max_length=200, null=False)


class OrderItem(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	count = models.PositiveIntegerField()

shop_app/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    img = forms.FileField()

    class Meta:
        model = Product
        fields = ['name', 'price', 'available', 'img']

shop_app/views.py
from django.shortcuts import render
import uuid
import os
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import CreateView, DeleteView, UpdateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import loader
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Product
from .forms import ProductForm
from .helper import handle_uploaded_file


def product_list(request):
    prod_list = Product.objects.order_by('-id').all()
    paginator = Paginator(prod_list, 5)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop_app/product_list.html', {'products': products})


def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_prod = form.save(commit=False)
            filename = str(uuid.uuid4())
            filepath = os.path.join(settings.IMG_ROOT, filename)
            rel_filepath = os.path.join(settings.MEDIA_URL, filename)
            handle_uploaded_file(request.FILES['img'], filepath)
            new_prod.img = rel_filepath
            new_prod.save()
            return redirect('shop_app:product_list')
    else:
        form = ProductForm()
    return render(request, 'shop_app/product_form.html', {'form': form})

class DeleteProduct(DeleteView):
    model = Product
    template_name = 'shop_app/product_delete.html'
    success_url = reverse_lazy('shop_app:product_list')


class UpdateProduct(UpdateView):
    model = Product
    fields = ['name','price', 'available']
    template_name = 'shop_app/product_update.html'
    success_url = reverse_lazy('shop_app:product_list')

shop_app/views/api_views.py
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.views.generic.list import ListView
from shop_app.models import Product, OrderItem, Order
from django.contrib.auth.models import User, Group
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.conf import settings
from rest_framework import viewsets, mixins
from rest_framework.response import Response
from shop_app.serializers import ProductSerializer, OrderItemSerializer, OrderSerializer
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated


class ProductViewSet(viewsets.ReadOnlyModelViewSet):
    """
    A ViewSet for listing or retrieving Products.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class OrderItemViewSet(mixins.CreateModelMixin,
                       mixins.ListModelMixin,
                       mixins.RetrieveModelMixin,
                       mixins.UpdateModelMixin,
                       viewsets.GenericViewSet):
    """
        A ViewSet for create, list, retrieve, update OrderItem.
    """
    queryset = OrderItem.objects.all()
    serializer_class = OrderItemSerializer


class OrderViewSet(mixins.ListModelMixin,
                   mixins.RetrieveModelMixin,
                   mixins.UpdateModelMixin,
                   viewsets.GenericViewSet):
    """
        A ViewSet for create, list, retrieve, update Order.
    """
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

shop_app/views/html_views.py
from django.shortcuts import render
import uuid
import os
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import CreateView, DeleteView, UpdateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.template import loader
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.conf import settings
from shop_app.models import Product, Order
from shop_app.forms import ProductForm
from shop_app.helper import handle_uploaded_file
from utils.tx_cloud.bucket import TXBucket


@staff_member_required
def dashboard(request):
    return render(request, 'shop_app/dashboard.html', {'user': request.user})


@staff_member_required
def product_list(request):
    prod_list = Product.objects.order_by('-id').all()
    paginator = Paginator(prod_list, 5)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request, 'shop_app/product_list.html', {'products': products})


@staff_member_required
def new_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            new_prod = form.save(commit=False)
            filename = str(uuid.uuid4())
            txb = TXBucket()
            url = txb.upload_img(fp=request.FILES['img'], bucket_file_name=filename)
            new_prod.img = url
            new_prod.save()
            return redirect('shop_app:product_list')
    else:
        form = ProductForm()
    return render(request, 'shop_app/product_form.html', {'form': form})


@staff_member_required
def order_list(request):
    all_orders = Order.objects.order_by('-id').all()
    paginator = Paginator(all_orders, 5)
    page = request.GET.get('page')
    try:
        orders = paginator.page(page)
    except PageNotAnInteger:
        orders = paginator.page(1)
    except EmptyPage:
        orders = paginator.page(paginator.num_pages)
    return render(request, 'shop_app/order_list.html', {'orders': orders})


class DeleteProduct(PermissionRequiredMixin, DeleteView):
    permission_required = 'is_staff'
    model = Product
    template_name = 'shop_app/product_delete.html'
    success_url = reverse_lazy('shop_app:product_list')


class UpdateProduct(PermissionRequiredMixin, UpdateView):
    permission_required = 'is_staff'
    model = Product
    fields = ['name','price', 'available']
    template_name = 'shop_app/product_update.html'
    success_url = reverse_lazy('shop_app:product_list')

shop_app/templates/shop_app/dashboard.html
{% extends "base.html" %}

{% block content %}
<!-- Breadcrumbs-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="#">Dashboard</a>
  </li>
  <li class="breadcrumb-item active">Overview</li>
</ol>

{% endblock %}

shop_app/templates/shop_app/order_list.html
{% extends "base.html" %}

{% block content %}

{% if orders %}
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>User</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
            <tr>
              <td>{{ order.user.username }}</td>
              <td>{{ order.status }}</td>
                <td></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a class="btn btn-primary" href="?page={{ orders.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ orders.number }} of {{ orders.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                <a class="btn btn-primary" href="?page={{ orders.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% else %}
    <p>No order are available.</p>
{% endif %}

{% endblock %}

shop_app/templates/shop_app/product_delete.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p class="alert alert-danger">Are you sure you want to delete "{{ object.name }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm" />
    <a class="btn btn-default" href="{% url 'shop_app:product_list'%}">No, Cancel</a>
</form>

{% endblock %}

shop_app/templates/shop_app/product_form.html
{% extends "base.html" %}

{% block content %}
<div class="row center-block">
    <div class="col-md-6">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
            {{ field.label_tag }}<br>
            {{ field.help_text|safe }}
            {{ field }}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">Save</button>
        </form>
    </div>
</div>
{% endblock %}

shop_app/templates/shop_app/product_list.html
{% extends "base.html" %}

{% block content %}
<div>
    <a class="btn btn-success" href="{% url 'shop_app:new_product' %}">New Product</a>
</div>
{% if products %}
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>Pic</th>
          <th>Availability</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for prod in products %}
            <tr>
              <td>{{ prod.name }}</td>
              <td>{{ prod.price }}</td>
              <td><img src="{{prod.img}}" width="120" height="90" /></td>
              <td>{{ prod.available }}</td>
              <td><a href="{% url 'shop_app:delete_product' prod.id %}">Delete</a></td>
              <td><a href="{% url 'shop_app:update_product' prod.id %}">Edit</a></td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if products.has_previous %}
                <a class="btn btn-primary" href="?page={{ products.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ products.number }} of {{ products.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                <a class="btn btn-primary" href="?page={{ products.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
{% else %}
    <p>No product are available.</p>
{% endif %}

{% endblock %}

shop_app/templates/shop_app/product_update.html
{% extends "base.html" %}

{% block content %}
<img src="{{object.img}}" width="120" height="90" />

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a class="btn btn-default" href="{% url 'shop_app:product_list'%}">Cancel</a>
</form>

{% endblock %}