server/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from user_app import views as user_app_Views

router = routers.DefaultRouter()
router.register(r'users', user_app_Views.UserViewSet)
router.register(r'groups', user_app_Views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop_app.urls')),
    path('api/user_app/', include('user_app.urls')),
    path('test/', include(router.urls)),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop_app/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import html_views, api_views
app_name = 'shop_app'
router = routers.DefaultRouter()
router.register(r'products', api_views.ProductViewSet)
router.register(r'order_items', api_views.OrderItemViewSet)
router.register(r'orders', api_views.OrderViewSet)
urlpatterns = [
    url(r'^$', html_views.dashboard, name='dashboard'),
    url(r'^products/$', html_views.product_list, name='product_list'),
    url(r'^api/', include(router.urls)),
    url(r'^product/new$', html_views.new_product, name='new_product'),
    url(r'^product/delete/(?P<pk>\d+)/$', html_views.DeleteProduct.as_view(), name='delete_product'),
    url(r'^product/(?P<pk>\d+)/update/$', html_views.UpdateProduct.as_view(), name='update_product'),
    url(r'^orders/$', html_views.order_list, name='order_list'),
]

server/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}Vitaeqo{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static '/sbadmin/css/sb-admin.css' %}">
  <link href="{% static '/sbadmin/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static '/sbadmin/vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
</head>
<body id="page-top">

  {% include "nav.html" %}

  <div id="wrapper">
    {% include "sidebar.html" %}

    <div id="content-wrapper">

      <div class="container-fluid">

      {% block content %}
      {% endblock %}



      </div>
      <!-- /.container-fluid -->

      <!-- Sticky Footer -->
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright © Vitaeqo 2019</span>
          </div>
        </div>
      </footer>

    </div>
    <!-- /.content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static '/sbadmin/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/sbadmin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static '/sbadmin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Page level plugin JavaScript-->
  <script src="{% static '/sbadmin/vendor/datatables/jquery.dataTables.js' %}"></script>
  <script src="{% static '/sbadmin/vendor/datatables/dataTables.bootstrap4.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static '/sbadmin/js/sb-admin.min.js' %}"></script>


</body>
</html>

server/templates/nav.html
 <nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="index.html">Vitaeqo</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Navbar Search -->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
          <button class="btn btn-primary" type="button">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Navbar -->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bell fa-fw"></i>
          <span class="badge badge-danger">9+</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow mx-1">
        <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope fa-fw"></i>
          <span class="badge badge-danger">7</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-user-circle fa-fw"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <a class="dropdown-item" href="#">Activity Log</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
        </div>
      </li>
    </ul>

  </nav>

server/templates/sidebar.html
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
  <li class="nav-item active">
    <a class="nav-link" href="index.html">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    </a>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'shop_app:product_list' %}">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Products</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'shop_app:order_list' %}">
      <i class="fas fa-fw fa-table"></i>
      <span>Orders</span></a>
  </li>
</ul>